Решение задач 4 блок 1,2,3
js-tasks-ru/jsbasic-20210420_stampout386 pull request #7
Opened 2021-05-06 12:16 UTC by stampout386

2021-05-06 12:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-06 14:54 UTC, SinimaWath requested changes

2021-05-06 14:54 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  friends.map(({firstName, lastName}) => {
Тут map, не нужен - так как ты не используешь результирующий массив.

Поэтому тут лучше forEach

2021-05-06 14:54 UTC, SinimaWath commented on 4-module/1-task/index.js
> +  let ul = document.createElement('ul');
Это же const

2021-05-06 14:54 UTC, SinimaWath commented on 4-module/2-task/index.js
> +const tableDiagonal = document.querySelector('table');
Это лишние, тебе в аргументы функции уже приходить табличка, так что не нужно тут ее запрашивать

2021-05-06 14:54 UTC, SinimaWath commented on 4-module/3-task/index.js
> +const table = document.querySelector('.js-teachers');
table уже передается в аргументы функции

2021-05-06 14:54 UTC, SinimaWath commented on 4-module/3-task/index.js
> +        td[1].innerHTML < 18 ? tr[i].style = "text-decoration: line-through" : null;
Тернарный оператор, не стоит использовать для операций по условию.

тут больше подходит if, давай на него перепишем

2021-05-06 15:23 UTC, stampout386 commented on 4-module/3-task/index.js
> +        td[1].innerHTML < 18 ? tr[i].style = "text-decoration: line-through" : null;
Блин ) у меня все на if было а я переписал специально все на ?  ) балбес)

2021-05-07 12:51 UTC, SinimaWath approved these changes

2021-05-07 12:52 UTC, merged