Решение 5 модуль задачи 1,2,3
js-tasks-ru/jsbasic-20210420_stampout386 pull request #8
Opened 2021-05-09 18:24 UTC by stampout386

2021-05-09 18:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-11 15:06 UTC, SinimaWath requested changes

2021-05-11 15:06 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  button.addEventListener('click',() => button.setAttribute('hidden' , true), {once: true});
hidden - стандартный атрибут, поэтому button.hidden

2021-05-11 15:06 UTC, SinimaWath commented on 5-module/2-task/index.js
> +           removeDiv.setAttribute('hidden', true);
Давай поменяем на стандартный атрибут

2021-05-11 15:06 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  buttonLeft.addEventListener('click', () => {
2 этих обработчика почти полностью одинаковые, давай попробуем вынести общие части в функции

2021-05-13 18:32 UTC, SinimaWath approved these changes

2021-05-13 18:33 UTC, merged